### ISSUE TITLE
node v0.10.0 - Module version mismatch

### ISSUE THREAD

**Issue by frankrowe** [Azure/node-sqlserver#119]
Did node v0.10 break some C++ APIs? The driver worked perfectly for me on node v.0.8x

C:\node_modules\msnodesql\lib\sqlserver.native.js:29
    throw e;
          ^
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\node_modules\msnodesql\lib\sqlserver.native.js:21:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Relevant code from node is
[https://github.com/joyent/node/blob/master/src/node.h#L204](https://github.com/joyent/node/blob/master/src/node.h#L204)

``` javascript
/**
 * When this version number is changed, node.js will refuse
 * to load older modules.  This should be done whenever
 * an API is broken in the C++ side, including in v8 or
 * other dependencies.
 */
#define NODE_MODULE_VERSION 0x000B /* v0.11 */
```

**Comment by DmitriyBerezin** [comment]
Good article - it is very helpfull. What is the reason that odbc32.lib hasn't declared in binding.gyp yet? It is a barrier to use normal installation via npm.
